name: nesteo_app
description: Nesting box management app for ringing associations.

version: 0.5.3+23

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  google_maps_flutter: ^0.5.21+7
  bloc: ^2.0.0
  flutter_bloc: ^2.0.0
  chopper: ^3.0.1
  image_picker: ^0.6.1+4
  path_provider: ^1.3.0
  path: ^1.6.4
  cupertino_icons: ^0.1.2
  meta: ^1.1.7
  equatable: ^0.6.0
  font_awesome_flutter: ^8.5.0
  geolocator: ^5.1.4
  back_button_interceptor: ^4.1.1
  intl: ^0.15.8
  datetime_picker_formfield: ^0.1.8
  flutter_secure_storage: ^3.3.1+1
  json_annotation: ^3.0.0
  english_words:
  flutter_typeahead: ^1.7.0
  http:
dev_dependencies:
  mockito: ^4.1.1
  flutter_launcher_icons: ^0.7.3
  chopper_generator: ^3.0.2
  build_runner: any
  json_serializable: ^3.2.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - locales/DE_DE.json
    - locales/EN_US.json
    - images/vogelhaus0.jpg
    - images/vogelhaus1.jpg
    - images/vogelhaus2.jpg
    - images/vogelhaus3.jpg
  fonts:
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand-Regular.ttf

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "icons/nesteo-logo-app.png"
  adaptive_icon_background: "#8BC34AFF"
  adaptive_icon_foreground: "icons/nesteo-logo-app-green.png"
