version: 2
jobs:
  test:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: flutter doctor
      - run: flutter test
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: flutter doctor
      - run: flutter -v build appbundle
      - run: mkdir tmp
      - run: mv build/app/outputs/bundle/release/app.aab tmp/
      - store_artifacts:
          path: tmp
workflows:
  version: 2
  test_and_build:
    jobs:
      - test
      - build
