version: 2
jobs:
  test:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: flutter doctor
      - run: flutter test
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: touch sign
      - run: ls
      - run: flutter doctor
      - run: flutter build apk
      - run: mkdir -p /tmp/artifacts
      - run: mv build/app/outputs/apk/release/* /tmp/artifacts/
      - store_artifacts:
          path: /tmp/artifacts
workflows:
  version: 2
  test_and_build:
    jobs:
      - test
      - build
